name: 'Setup Nim compiler and tools'
description: 'Download and install the selected Nim nightly build'

inputs:
  version:
    description: 'Which nightly-tracked branch should be fetched'
    required: true
    default: 'devel'
  path:
    description: 'The path which the compiler will be downloaded to'
    required: false
    default: 'nim'
  add-to-path:
    description: 'Whether the compiler should be added to PATH'
    required: false
    default: true

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'download-cloud'
  color: 'yellow'
